<?php
function dna_menu() {
    // set up
    $items['dna'] = array(
        'title' => 'DNA',
        'access callback' => TRUE,
        'page callback' => 'drupal_get_form',
        'page arguments' => array('dna_form'),
        'type' => MENU_NORMAL_ITEM,
    );

    $items['dna_success_page'] = array(
        'title' => 'success',
        'page callback' => 'dna_success',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    return $items;
}

// Build form
function dna_form() {
    $form['dna_input'] = array(
        '#title' => 'Input the first half of your DNA helix!',
        '#type' => 'textfield',
        '#required' => TRUE,
        '#element_validate' => array('element_validate_input'),
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'Go!',
    );
    return $form;
}

// Validate Input
function element_validate_input($element) {
    $valid_inputs = array('a', 't', 'c', 'g', 'A', 'T', 'C', 'G');
    $inputted_array = str_split($element['#value']);
    foreach($inputted_array as $input) {
        if(in_array($input, $valid_inputs) == false) {
            form_error($element, t("That's not a valid input, please enter only the following: A, T, C, G, a, t, c, g"));
        }
    }
}


// Run logic using user input
function dna_form_submit($form, &$form_state) {
    $_SESSION['helix1'] = strtoupper($form_state['values']['dna_input']);
    $_SESSION['helix2'] = array_map('dnaGenerator', str_split($_SESSION['helix1']));
    $form_state['redirect'] = 'dna_success_page';
}

// Create a new array using conditionals
function dnaGenerator($input) {
    if($input === 'A') {
		$input = 'T';
	} elseif($input === 'T') {
		$input = 'A';
	} elseif($input === 'C') {
		$input = 'G';
	} elseif($input === 'G') {
		$input = 'C';
	}
	return $input;
}

// Take user to success page and display returned value
function dna_success() {
    $helix1 = $_SESSION['helix1'];
    $helix2 = implode($_SESSION['helix2']);
    return 'Your first strand is:  <b>' . $helix1 . '</b><br><br> Your second strand is:  <b>' . $helix2 . '</b>';
}
