<?php
function mymodule_menu() {
    $items['path-to-ajax/%/%'] = array(
            'access arguments' => array('access content'),
            'page callback' => 'mymodule_ajax_callback',
            'page arguments' => array(1,2),
            'type' => MENU_CALLBACK,
    );
    return $items;
}

function mymodule_ajax_callback($js, $node_id) {
    $node = node_load($node_id);

    if($js == 'nojs') {
        drupal_goto('node/' . $node->nid);
    }

    // Render node array into HTML
    $build = node_view($node);
    $html = render($build);

    // Set up ajax command that will insert node's html into '#wrapper' div
    $commands = array();
    $commands[] = ajax_command_html('#wrapper', $html);

    // Render command into json formal and print to browser
    print ajax_render($commands);
    exit;
}
